# Задание 1

In [2]:
import numpy as np

In [3]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [4]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [5]:
mean_a = a.mean(axis=0)

In [6]:
print(mean_a)

[2.  8.4]


# Задание 2

In [7]:
a_centered = a - mean_a

In [8]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


# Задание 3

In [15]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
print(a_centered_sp)

8.0


In [16]:
cov = a_centered_sp/4
cov

2.0

# Задание 4

In [17]:
cov2 = np.cov(np.transpose(a))
cov2

array([[1. , 2. ],
       [2. , 4.3]])